export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XDG_CACHE_HOME=$HOME/.cache
export XDG_CONFIG_HOME=$HOME/.config
export XAUTHORITY=$XDG_RUNTIME_DIR/Xauthority
export WINEPREFIX=$XDG_DATA_HOME/wine
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"                                                                                                                              
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java                                                                                                                
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
export KDEHOME="$XDG_CONFIG_HOME"/kde
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export ANDROID_HOME="$XDG_DATA_HOME"/android
export XDG_DATA_DIRS=/var/lib/flatpak/exports/share:$HOME/.local/share/flatpak/exports/share:$XDG_DATA_DIRS
export ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"
export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export ICEAUTHORITY="$XDG_CACHE_HOME"/ICEauthority
export GOPATH="$XDG_DATA_HOME"/go
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export XDG_DESKTOP_DIR="$HOME/dsk"
export XDG_DOWNLOAD_DIR="$HOME/dl"
export XDG_TEMPLATES_DIR="$HOME/tpl"
export XDG_PUBLICSHARE_DIR="$HOME/pub"
export XDG_DOCUMENTS_DIR="$HOME/doc"
export XDG_MUSIC_DIR="$HOME/mus"
export XDG_PICTURES_DIR="$HOME/pic"
export XDG_VIDEOS_DIR="$HOME/vid"

