directory: ~/mus
plugins: deezer fromfilename fetchart lyrics fish edit embedart smartplaylist mpdupdate play
smartplaylist:
  relative_to: ~/mus
  playlist_dir: ~/mus
  playlists:
    - name: all.m3u
      query: ''
    - name: vibe.m3u
      query: ['artist:Phaseone', 'artist:Apashe', 'artist:FWLR', 'artist:Noisia', 'artist:F.O.O.L', 'artist:Habstrakt', 'artist: Skrillex', 'artist: Whipped Cream', 'artist:GG Magree', 'artist:RAM']
    - name: ru.m3u
      query: ['artist::[а-я]', 'artist:sunburst, the korea , OSCAL, Hard Bass School', 'song:bochka, vodka', 'album: action']
mpd:
  host: localhost
  port: 6600
play:
  command: /home/napca/.config/beets/play.sh

deezer:
  source_weight: 0.0
spotify: 
  source_weight: 0.5
lyrics:
  auto: no
fetchart:
  auto: no
embedart:
  auto: no
  remove_art_file: no
library: ~/.config/beets/musiclibrary.db
import:
  move: yes
  copy: no
  write: yes
  duplicate_action: merge
  group_albums: yes
aunique:
  keys: albumartist album
  disambiguators: albumtype year label
  bracket: '[]'

